### ISSUE TITLE
Create release procedure

### ISSUE THREAD

**Issue by oladahl** [accellera-official/cci#285]
Steps to make a release
- create release tag
- when creating this tag, create the configure file and the tarball (there is a script for this)
- ensure that the tarball can be downloaded from https://accellera.org/downloads/standards/systemc – just link to the GitHub

Consider using GitHub Actions for this task

Pipeclean this flow by doing a release candidate!

**Comment by aut0** [comment]
Summary of discussion during meeting:
- Automatic Release Text Generation still to do
- Automatic Release Generation from Tag mostly working

Will send PR once complete.

**Comment by barnasc** [comment]
Note that the release procedure should also update the version number and release date in https://github.com/accellera-official/cci/blob/master/configure.ac
