### ISSUE TITLE
Update Release Documents (Changelog, Releasenotes,...) for 1.0.1 release

### ISSUE THREAD

**Issue by barnasc** [accellera-official/cci#299]
Proposed text for the release
* Introduce build flows: automake, cmake and msvc
* Dependency to RapidJSON managed via automake and cmake build flow
* Cleanup of examples and related presentations, remove BOOST dependency

**Comment by aut0** [comment]
Remember to update RELEASENOTES.md as well:
- Remove "Formerly supported platforms"
- Align "Supported platforms" with SystemC
