### ISSUE TITLE
RapidJSON package issue

### ISSUE THREAD

**Issue by markfoodyburton** [accellera-official/cci#307]
https://github.com/accellera-official/cci/blob/f84266f01f88c917f7b0ae12a4d738009f47368f/src/CMakeLists.txt#L140

Should this be RapidJSON?

**Comment by aut0** [comment]
I think it's okay.
What issue are you seeing?

**Comment by aut0** [comment]
Looks okay to me.
What is the issue?

BR,
Lukas

**Comment by markfoodyburton** [comment]
On "some" operating systems, on some days, with some weather conditions, it seems to prefer RapidJSON to match the package name (rather than RAPIDJSON)
