### ISSUE TITLE
add support for disabling the SystemC compile checks - similar to UVM-SystemC and SystemC AMS

### ISSUE THREAD

**Issue by maveric2** [accellera-official/cci#312]
Hi,

sometimes it's quite handy to disable the compile checks for SystemC e.g. in case of cross-compilation.
This is done by "--disable-systemc_compile_check" in the other cases.

KR

**Comment by maveric2** [comment]
[cci-1.0.1-disable-systemc_compile_check.patch](https://github.com/accellera-official/cci/files/14745026/cci-1.0.1-disable-systemc_compile_check.patch)

**Comment by aut0** [comment]
The automake flow will be deprecated and removed soon.
Please consider moving to cmake.
