### ISSUE TITLE
in-tree build for mingw-w64 fails (doc folder)

### ISSUE THREAD

**Issue by maveric2** [accellera-official/cci#314]
/usr/bin/install: '../../docs/cci/archived/guidelines.txt' and 'c:/j/ww64/cci-1.0.1/docs/cci/archived/guidelines.txt' are the same file
/usr/bin/install: '../../docs/cci/archived/notes.txt' and 'c:/j/ww64/cci-1.0.1/docs/cci/archived/notes.txt' are the same file
make[2]: *** [Makefile:367: install-nobase_docDATA] Error 1

How to repoduce:
* install msys64 with gcc or clang
* cd cci-1.0.1
* setenv CCI_HOME `pwd`
* config/bootstrap
* mkdir obj-$TARGET_ARCH
* cd obj-$TARGET_ARCH
* // in tree build
* ../configure --prefix=${CCI_HOME}

**Comment by aut0** [comment]
The automake flow will be deprecated and removed soon.
Please consider moving to cmake.
